/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.gnr.sgp.view.formulario;

/**
 *
 * @author Guilherme
 */

import com.gnr.sgp.modelo.conexao.Conexao;
import java.sql.*;
import com.gnr.sgp.modelo.conexao.ConexaoMysql;
import javax.swing.JOptionPane;

public class TelaUsuario extends javax.swing.JInternalFrame {

   Conexao conexao = null;
   PreparedStatement pst = null;
   ResultSet rs = null;
   
    public TelaUsuario() {
        initComponents();
        conexao = new ConexaoMysql();
    }
    
    private void consultar(){
        
        String sql = "select * from usuarios where login=?";
        try {
            pst=conexao.obterConexao().prepareStatement(sql);
            pst.setString(1, jTextUsuLogin.getText());
            rs=pst.executeQuery();
            if (rs.next()) {
                jTextUsuNome.setText(rs.getString(5));
                jTextUsuLogin.setText(rs.getString(2));
                jPassUsuSenha.setText(rs.getString(3));
                jComboUsuPerfil.setSelectedItem(rs.getString(4));
            } else {
                JOptionPane.showMessageDialog(null, "Usuário não encontrado.");
                jTextUsuNome.setText(null);
                jTextUsuLogin.setText(null);
                jPassUsuSenha.setText(null);
                jComboUsuPerfil.setSelectedItem(null);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
               
        }
    }
    
    public static String maxlength(String str) {
            String valor = "";
            if(str.length() > 4){
	        valor = str.substring(0,4);
                str = valor;
            }
	    return str;
    } 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUsuNome = new javax.swing.JLabel();
        jLabelUsuLogin = new javax.swing.JLabel();
        jLabelUsuPerfil = new javax.swing.JLabel();
        jTextUsuLogin = new javax.swing.JTextField();
        jTextUsuNome = new javax.swing.JTextField();
        jLabelUsuSenha = new javax.swing.JLabel();
        jPassUsuSenha = new javax.swing.JPasswordField();
        jComboUsuPerfil = new javax.swing.JComboBox<>();
        jButtonUsuAdicionar = new javax.swing.JButton();
        jButtonUsuConsultar = new javax.swing.JButton();
        jButtonUsuEditar = new javax.swing.JButton();
        jButtonUsuDeletar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Usuários");
        setMinimumSize(new java.awt.Dimension(680, 480));
        setPreferredSize(new java.awt.Dimension(820, 620));

        jLabelUsuNome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelUsuNome.setText("Nome:");

        jLabelUsuLogin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelUsuLogin.setText("Login:");

        jLabelUsuPerfil.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelUsuPerfil.setText("Perfil:");

        jTextUsuLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextUsuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUsuLoginActionPerformed(evt);
            }
        });

        jTextUsuNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextUsuNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUsuNomeActionPerformed(evt);
            }
        });

        jLabelUsuSenha.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelUsuSenha.setText("Senha:");

        jPassUsuSenha.setMaximumSize(new java.awt.Dimension(64, 22));
        jPassUsuSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassUsuSenhaActionPerformed(evt);
            }
        });

        jComboUsuPerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "consulta", "admin" }));
        jComboUsuPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboUsuPerfilActionPerformed(evt);
            }
        });

        jButtonUsuAdicionar.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\resources\\create.png"));
        jButtonUsuAdicionar.setToolTipText("Adicionar");
        jButtonUsuAdicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUsuAdicionar.setPreferredSize(new java.awt.Dimension(80, 80));
        jButtonUsuAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuAdicionarActionPerformed(evt);
            }
        });

        jButtonUsuConsultar.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\resources\\read.png"));
        jButtonUsuConsultar.setToolTipText("Pesquisar");
        jButtonUsuConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUsuConsultar.setMaximumSize(new java.awt.Dimension(80, 80));
        jButtonUsuConsultar.setPreferredSize(new java.awt.Dimension(80, 80));
        jButtonUsuConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuConsultarActionPerformed(evt);
            }
        });

        jButtonUsuEditar.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\resources\\update.png"));
        jButtonUsuEditar.setToolTipText("Editar");
        jButtonUsuEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUsuEditar.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonUsuDeletar.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\resources\\delete.png"));
        jButtonUsuDeletar.setToolTipText("Deletar");
        jButtonUsuDeletar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUsuDeletar.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonUsuAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jButtonUsuConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUsuNome)
                            .addComponent(jLabelUsuLogin))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextUsuLogin)
                            .addComponent(jTextUsuNome, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUsuSenha)
                            .addComponent(jLabelUsuPerfil))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPassUsuSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboUsuPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonUsuEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jButtonUsuDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsuNome)
                    .addComponent(jTextUsuNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUsuSenha)
                    .addComponent(jPassUsuSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsuLogin)
                    .addComponent(jLabelUsuPerfil)
                    .addComponent(jComboUsuPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextUsuLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonUsuAdicionar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUsuConsultar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonUsuEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonUsuDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(135, 135, 135))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPassUsuSenha, jTextUsuLogin, jTextUsuNome});

        setBounds(0, 0, 820, 620);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextUsuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUsuLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUsuLoginActionPerformed

    private void jTextUsuNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUsuNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUsuNomeActionPerformed

    private void jPassUsuSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassUsuSenhaActionPerformed
        jPassUsuSenha.setText(maxlength(jPassUsuSenha.getText()));
    }//GEN-LAST:event_jPassUsuSenhaActionPerformed

    private void jButtonUsuAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuAdicionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUsuAdicionarActionPerformed

    private void jButtonUsuConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuConsultarActionPerformed

        consultar();
    }//GEN-LAST:event_jButtonUsuConsultarActionPerformed

    private void jComboUsuPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboUsuPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboUsuPerfilActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonUsuAdicionar;
    private javax.swing.JButton jButtonUsuConsultar;
    private javax.swing.JButton jButtonUsuDeletar;
    private javax.swing.JButton jButtonUsuEditar;
    private javax.swing.JComboBox<String> jComboUsuPerfil;
    private javax.swing.JLabel jLabelUsuLogin;
    private javax.swing.JLabel jLabelUsuNome;
    private javax.swing.JLabel jLabelUsuPerfil;
    private javax.swing.JLabel jLabelUsuSenha;
    private javax.swing.JPasswordField jPassUsuSenha;
    private javax.swing.JTextField jTextUsuLogin;
    private javax.swing.JTextField jTextUsuNome;
    // End of variables declaration//GEN-END:variables
}
