/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.gnr.sgp.view.formulario;

/**
 *
 * @author Guilherme
 */
import com.gnr.sgp.modelo.conexao.Conexao;
import java.sql.*;
import com.gnr.sgp.modelo.conexao.ConexaoMysql;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import net.proteanit.sql.DbUtils;

public class TelaConsultaUsuario extends javax.swing.JInternalFrame {

    Conexao conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public TelaConsultaUsuario() {

        initComponents();
        conexao = new ConexaoMysql();

        setLocation(-5, -5);
        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentMoved(ComponentEvent e) {
                // Define a posição do componente para (0, 0)
                setLocation(-5, -5);
            }
        });
    }

    public void pesquisarUsuarioId() {
        String sql = String.format("SELECT * FROM usuarios WHERE id like ?");
        try {
            pst = conexao.obterConexao().prepareStatement(sql);
            pst.setString(1, jTextUsuBusca.getText() + "%");
            rs = pst.executeQuery();

            jTableForn.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public void pesquisarUsuarioLogin() {
        String sql = String.format("SELECT * FROM usuarios WHERE login like ?");
        try {
            pst = conexao.obterConexao().prepareStatement(sql);
            pst.setString(1, jTextUsuBusca.getText() + "%");
            rs = pst.executeQuery();

            jTableForn.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public void pesquisarUsuarioNome() {
        String sql = String.format("SELECT * FROM usuarios WHERE nome like ?");
        try {
            pst = conexao.obterConexao().prepareStatement(sql);
            pst.setString(1, jTextUsuBusca.getText() + "%");
            rs = pst.executeQuery();

            jTableForn.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    public void pesquisarUsuarioTipo() {
        String sql = String.format("SELECT * FROM usuarios WHERE tipo like ?");
        try {
            pst = conexao.obterConexao().prepareStatement(sql);
            pst.setString(1, jTextUsuBusca.getText() + "%");
            rs = pst.executeQuery();

            jTableForn.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableForn = new javax.swing.JTable();
        jComboUsuPesquisa = new javax.swing.JComboBox<>();
        jTextUsuBusca = new javax.swing.JTextField();
        jLabelUsuBusca = new javax.swing.JLabel();
        jLabelFornCampos = new javax.swing.JLabel();

        setBackground(new java.awt.Color(227, 234, 227));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setTitle("Usuários");
        setMinimumSize(new java.awt.Dimension(680, 480));
        setPreferredSize(new java.awt.Dimension(730, 545));

        jTableForn = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTableForn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTableForn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Login", "Nome", "Tipo"
            }
        ));
        jTableForn.getTableHeader().setReorderingAllowed(false);
        jTableForn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFornMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableForn);

        jComboUsuPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id", "Login", "Nome", "Tipo" }));
        jComboUsuPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboUsuPesquisaActionPerformed(evt);
            }
        });

        jTextUsuBusca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextUsuBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextUsuBuscaKeyReleased(evt);
            }
        });

        jLabelUsuBusca.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\resources\\busca.png"));
        jLabelUsuBusca.setText(" ");

        jLabelFornCampos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelFornCampos.setText("* Campos obrigatórios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboUsuPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextUsuBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelUsuBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addComponent(jLabelFornCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelFornCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextUsuBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboUsuPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabelUsuBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(0, 0, 730, 545);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableFornMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFornMouseClicked
        //evento para setar os campos clicando com o botao esquerdo do mouse
     
    }//GEN-LAST:event_jTableFornMouseClicked

    private void jComboUsuPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboUsuPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboUsuPesquisaActionPerformed

    private void jTextUsuBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextUsuBuscaKeyReleased
        //enquanto for digitando fazer isto
        if (jComboUsuPesquisa.getSelectedItem().toString() == "Id") {
            pesquisarUsuarioId();
        } else if (jComboUsuPesquisa.getSelectedItem().toString() == "Login") {
            pesquisarUsuarioLogin();
        } else if (jComboUsuPesquisa.getSelectedItem().toString() == "Nome") {
            pesquisarUsuarioNome();
        } else if (jComboUsuPesquisa.getSelectedItem().toString() == "Tipo") {
            pesquisarUsuarioTipo();
        }

    }//GEN-LAST:event_jTextUsuBuscaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboUsuPesquisa;
    private javax.swing.JLabel jLabelFornCampos;
    private javax.swing.JLabel jLabelUsuBusca;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableForn;
    public javax.swing.JTextField jTextUsuBusca;
    // End of variables declaration//GEN-END:variables
}
