/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.gnr.sgp.view.formulario;

import com.gnr.sgp.modelo.dao.FornecedoresDao;
import com.gnr.sgp.modelo.dao.UsuariosDao;
import com.gnr.sgp.modelo.dominio.Fornecedores;
import com.gnr.sgp.modelo.dominio.Usuarios;
import javax.swing.JOptionPane;

/**
 *
 * @author Guilherme
 */
public class TelaFornecedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaFornecedor
     */
    public TelaFornecedor() {
        initComponents();
    }
    
    public void adicionar(){
         if ((jTextFornNome.getText().isEmpty() || jTextFornTelefone.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios.");
        } else {

            Fornecedores fornecedor = new Fornecedores(0l, jTextFornNome.getText(), jTextFornTelefone.getText(), jTextFornEmail.getText(), jTextFornEndereco.getText());

            FornecedoresDao fornecedoresDao = new FornecedoresDao();
            fornecedoresDao.adicionar(fornecedor);
            
            limpaCampos();
        }
    }
    
    public void limpaCampos() {
        jTextFornBusca.setText(null);
        jTextFornNome.setText(null);
        jTextFornTelefone.setText(null);
        jTextFornEmail.setText(null);
        jTextFornEndereco.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonFornAdicionar = new javax.swing.JButton();
        jButtonFornEditar = new javax.swing.JButton();
        jButtonFornDeletar = new javax.swing.JButton();
        jLabelFornCampos = new javax.swing.JLabel();
        jLabelFornNome = new javax.swing.JLabel();
        jTextFornNome = new javax.swing.JTextField();
        jLabelFornEndereco = new javax.swing.JLabel();
        jTextFornEndereco = new javax.swing.JTextField();
        jLabelFornTelefone = new javax.swing.JLabel();
        jTextFornTelefone = new javax.swing.JTextField();
        jLabelFornEmail = new javax.swing.JLabel();
        jTextFornEmail = new javax.swing.JTextField();
        jTextFornBusca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableForn = new javax.swing.JTable();
        jLabelFornBusca = new javax.swing.JLabel();

        setTitle("Fornecedores");
        setMinimumSize(new java.awt.Dimension(680, 480));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(820, 620));

        jButtonFornAdicionar.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\resources\\create.png"));
        jButtonFornAdicionar.setToolTipText("Adicionar");
        jButtonFornAdicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonFornAdicionar.setPreferredSize(new java.awt.Dimension(80, 80));
        jButtonFornAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFornAdicionarActionPerformed(evt);
            }
        });

        jButtonFornEditar.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\resources\\update.png"));
        jButtonFornEditar.setToolTipText("Editar");
        jButtonFornEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonFornEditar.setPreferredSize(new java.awt.Dimension(80, 80));
        jButtonFornEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFornEditarActionPerformed(evt);
            }
        });

        jButtonFornDeletar.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\resources\\delete.png"));
        jButtonFornDeletar.setToolTipText("Deletar");
        jButtonFornDeletar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonFornDeletar.setPreferredSize(new java.awt.Dimension(80, 80));
        jButtonFornDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFornDeletarActionPerformed(evt);
            }
        });

        jLabelFornCampos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelFornCampos.setText("* Campos obrigatórios");

        jLabelFornNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelFornNome.setText("* Nome:");

        jTextFornNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFornNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFornNomeActionPerformed(evt);
            }
        });

        jLabelFornEndereco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelFornEndereco.setText("Endereço:");

        jTextFornEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabelFornTelefone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelFornTelefone.setText("* Telefone:");

        jTextFornTelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabelFornEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelFornEmail.setText("Email:");

        jTextFornEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextFornBusca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTableForn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTableForn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Endereço", "Telefone", "Email"
            }
        ));
        jScrollPane1.setViewportView(jTableForn);
        if (jTableForn.getColumnModel().getColumnCount() > 0) {
            jTableForn.getColumnModel().getColumn(0).setPreferredWidth(15);
        }

        jLabelFornBusca.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\resources\\busca.png"));
        jLabelFornBusca.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabelFornEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelFornNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabelFornTelefone)
                                    .addComponent(jLabelFornEmail))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFornEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFornTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFornNome, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFornEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 123, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jTextFornBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelFornBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelFornCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jButtonFornAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(jButtonFornEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jButtonFornDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelFornCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFornBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabelFornBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFornNome)
                    .addComponent(jTextFornNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFornEndereco)
                    .addComponent(jTextFornEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFornTelefone)
                    .addComponent(jTextFornTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFornEmail)
                    .addComponent(jTextFornEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonFornDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFornEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFornAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFornAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFornAdicionarActionPerformed
        adicionar();
    }//GEN-LAST:event_jButtonFornAdicionarActionPerformed

    private void jButtonFornEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFornEditarActionPerformed
     
    }//GEN-LAST:event_jButtonFornEditarActionPerformed

    private void jButtonFornDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFornDeletarActionPerformed
       
    }//GEN-LAST:event_jButtonFornDeletarActionPerformed

    private void jTextFornNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFornNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFornNomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFornAdicionar;
    private javax.swing.JButton jButtonFornDeletar;
    private javax.swing.JButton jButtonFornEditar;
    private javax.swing.JLabel jLabelFornBusca;
    private javax.swing.JLabel jLabelFornCampos;
    private javax.swing.JLabel jLabelFornEmail;
    private javax.swing.JLabel jLabelFornEndereco;
    private javax.swing.JLabel jLabelFornNome;
    private javax.swing.JLabel jLabelFornTelefone;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableForn;
    public javax.swing.JTextField jTextFornBusca;
    public javax.swing.JTextField jTextFornEmail;
    public javax.swing.JTextField jTextFornEndereco;
    public javax.swing.JTextField jTextFornNome;
    public javax.swing.JTextField jTextFornTelefone;
    // End of variables declaration//GEN-END:variables
}
